# Generated by Django 3.0.2 on 2020-05-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200517_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Memo',
            new_name='memo',
        ),
    ]
